networks:
  demowebapp:

services:
  ccmsdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Krishna123#
    networks:
      - demowebapp
  ccms3:
    container_name: ccms3-web-app
    image: ${DOCKER_REGISTRY-}ccms3
    build:
      context: .
      dockerfile: CCMS3/Dockerfile
    ports:
      - 8001:8080
    depends_on:
      - ccmsdb
    environment:
      - DB_HOST=ccmsdb
      - DB_NAME=ccms
      - DB_SA_PASSWORD=Krishna123#
    networks:
      - demowebapp
  frontend:
    container_name: ccms-frontend
    build:
      context: D:/Synergech_Assessments/frontend/project/ccms # Adjust this path based on your directory structure
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Frontend will be accessible on port 3000
    depends_on:
      - ccms3
    networks:
      - demowebapp
    environment:
      - VITE_REACT_APP_API_BASE_URL=http://localhost:8001/api